---
- include: mysql.yml
  tags: rundeck-mysql
  when: rd_mysql_enabled

- include: nginx.yml
  tags: rundeck-nginx

- name: ensure /var/rundeck cirectory exists
  file:
    path: /var/rundeck
    state: directory
    owner: rundeck
    group: rundeck
    mode: 0755

- name: Add apt signing key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ rundeck_apt_key }}"

- name: Add rundeck repository
  apt_repository:
    repo: 'deb https://rundeck.bintray.com/rundeck-deb /'
    state: present
    filename: rundeck

- name: Install Rundeck Server and cli
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  with_items:
    - rundeck={{ rundeck_version }}*
    - rundeck-cli

- name: remove upstart scripts
  file:
    path: /etc/init/rundeckd.conf
    state: absent

- debug: var=rundeck_plugins
  tags: plugins

- name: Download plugins
  get_url:
    url: "{{ item }}"
    dest: "/var/lib/rundeck/libext/{{ item.split('/')[-1] }}"
    mode: 0644
  with_items: "{{ rundeck_plugins }}"
  notify: restart rundeckd
  tags: plugins

- name: remove plugins
  file:
    path: "/var/lib/rundeck/libext/{{ item |d(omit) }}"
    state: absent
  with_items: "{{ rundeck_plugins_removed }}"
  notify: restart rundeckd
  tags: plugins

- name: modify config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/rundeck/{{ item }}"
    owner: rundeck
    group: rundeck
    mode: 0640
  with_items:
    - framework.properties
    - rundeck-config.properties
    - log4j.properties
  notify: restart rundeckd
  tags:
    - rundeck-login-module
    - rundeck-properties
    - plugins

- name: Add login module config
  template:
    src: "jaas-{{ rd_login_module }}.conf.j2"
    dest: "/etc/rundeck/jaas-{{ rd_login_module }}.conf"
    owner: rundeck
    group: rundeck
    mode: 0640
  notify: restart rundeckd
  when: rd_login_module is defined
  tags:
    - rundeck-login-module

- name: Parse realm properties
  template:
    src: realm.properties.j2
    dest: /etc/rundeck/realm.properties
    owner: rundeck
    group: rundeck
    mode: 0640
  notify: restart rundeckd
  when: rd_login_module == "propertyfile"
  tags:
    - rundeck-login-module

- name: export login module config
  template:
    src: "rundeckd.j2"
    dest: "/etc/default/rundeckd"
    owner: rundeck
    group: rundeck
    mode: 0640
  notify: restart rundeckd
  when: rd_login_module is defined
  tags:
    - rundeck-login-module

- name: modify config that not require restart
  template:
    src: "{{ item }}.j2"
    dest: "/etc/rundeck/{{ item }}"
    owner: rundeck
    group: rundeck
    mode: 0640
  with_items:
    - admin.aclpolicy
    - rundeckadmin.aclpolicy
    - apitoken.aclpolicy
  tags:
    - rundeck-aclpolicy

- name: put limits.d file
  template:
    src: limits.conf
    dest: /etc/security/limits.d
    owner: root
    group: root
    mode: 0644

- name: modify directory permission
  file:
    path: /etc/rundeck
    state: directory
    owner: rundeck
    group: rundeck
    recurse: yes

- name: modify directory permission
  file:
    path: /var/lib/rundeck
    state: directory
    owner: rundeck

- include: overrides.yml
  when: rundeck_overrides | length > 0
  notify: restart rundeckd
  tags: rundeck-overrides

- name: "Rundeck | copy rundeck systemd file"
  template:
    src: "rundeck.service.j2"
    dest: "/etc/systemd/system/rundeck.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart rundeckd
  when: ansible_service_mgr == "systemd"

- name: enable rundeckd and ensure it is started
  systemd:
    name: rundeckd
    enabled: yes
    state: started
    daemon_reload: yes

- include: projects.yml
  tags: rundeck-projects
